import 'package:flutter/widgets.dart';
import 'package:provider/provider.dart';

import '../providers/app_state.dart';

const Map<String, Map<String, String>> _strings = {
  'uk': {
    'appName': 'ДнД - Компаньон',
    'donateButton': 'Донатик на вкусняшку',
    'settings': 'Налаштування',
    'language': 'Мова',
    'english': 'Англійська',
    'russian': 'Російська',
    'ukrainian': 'Українська',
    'googleAccount': 'Підключити Google акаунт',
    'shareCharacter': 'Поділитися персонажем',
    'printPdf': 'Роздрукувати PDF файл',
    'shareLink': 'Посилання на персонажа',
    'close': 'Закрити',
    'comingSoon': 'Скоро буде доступно',
    'character': 'Персонаж',
    'armory': 'Арморі',
    'combat': 'Бойові',
    'spells': 'Заклинання',
    'abilities': 'Вміння',
    'inventory': 'Інвентар',
    'dice': 'Кубики',
    'notes': 'Нотатки',
    'notes_hint': 'Введіть ваші нотатки тут...',
    'notes_description': 'Особисті нотатки персонажа',
    'notes_saved': 'Нотатки збережено',
    'save': 'Зберегти',
    'theme': 'Тема',
    'light_theme': 'Світла тема',
    'dark_theme': 'Темна тема',
    'theme_description': 'Кофейна світла або пергаментна темна палітра',
  },
  'ru': {
    'appName': 'ДнД - Компаньон',
    'donateButton': 'Донатик на вкусняшку',
    'settings': 'Настройки',
    'language': 'Язык',
    'english': 'Английский',
    'russian': 'Русский',
    'ukrainian': 'Украинский',
    'googleAccount': 'Подключить Google аккаунт',
    'shareCharacter': 'Поделиться персонажем',
    'printPdf': 'Распечатать PDF файл',
    'shareLink': 'Ссылка на персонажа',
    'close': 'Закрыть',
    'comingSoon': 'Скоро будет доступно',
    'character': 'Персонаж',
    'armory': 'Армори',
    'combat': 'Боевые',
    'spells': 'Заклинания',
    'abilities': 'Умения',
    'inventory': 'Инвентарь',
    'dice': 'Кубики',
    'notes': 'Заметки',
    'notes_hint': 'Введите ваши заметки здесь...',
    'notes_description': 'Личные заметки персонажа',
    'notes_saved': 'Заметки сохранены',
    'save': 'Сохранить',
    'theme': 'Тема',
    'light_theme': 'Светлая тема',
    'dark_theme': 'Темная тема',
    'theme_description': 'Кофейная светлая или пергаментная тёмная палитра',
  },
  'en': {
    'appName': 'DnD - Companion',
    'donateButton': 'Buy me a snack',
    'settings': 'Settings',
    'language': 'Language',
    'english': 'English',
    'russian': 'Russian',
    'ukrainian': 'Ukrainian',
    'googleAccount': 'Connect Google account',
    'shareCharacter': 'Share character',
    'printPdf': 'Print PDF file',
    'shareLink': 'Character link',
    'close': 'Close',
    'comingSoon': 'Coming soon',
    'character': 'Character',
    'armory': 'Armory',
    'combat': 'Combat',
    'spells': 'Spells',
    'abilities': 'Abilities',
    'inventory': 'Inventory',
    'dice': 'Dice',
    'notes': 'Notes',
    'notes_hint': 'Enter your notes here...',
    'notes_description': 'Character personal notes',
    'notes_saved': 'Notes saved',
    'save': 'Save',
    'theme': 'Theme',
    'light_theme': 'Light theme',
    'dark_theme': 'Dark theme',
    'theme_description': 'Coffee light or parchment dark palette',
  },
};

String tr(BuildContext context, String key) {
  final code = context.watch<AppState>().languageCode;
  return _strings[code]?[key] ?? _strings['uk']![key] ?? key;
}

String trRead(BuildContext context, String key) {
  final code = context.read<AppState>().languageCode;
  return _strings[code]?[key] ?? _strings['uk']![key] ?? key;
}
